language: csharp
solution: RandomizerSharp.sln
before_install:
  - mkdir -p .nuget
  - wget -O .nuget/nuget.exe https://dist.nuget.org/win-x86-commandline/latest/nuget.exe
  - mono .nuget/nuget.exe # Output NuGet's version number
install:
  - mono .nuget/nuget.exe restore RandomizerSharp.sln -Verbosity detailed
  - mono .nuget/nuget.exe install NUnit.Runners -Version 3.6.1 -OutputDirectory ./src/packages
  - nuget install NUnit.Runners -Version 3.6.1 -OutputDirectory testrunner
script:
  - xbuild /p:Configuration=Release RandomizerSharp.sln
  - mono ./testrunner/NUnit.Runners.3.6.1/tools/nunit-console.exe ./RandomizerSharp.Tests/bin/Release/RandomizerSharp.Tests.dll